### ISSUE TITLE
Naming overlap: alantech/highlightjs-alan and highlightjs/highlightjs-alan

### ISSUE THREAD

**Issue by joshgoebel** [alantech/highlightjs-alan#2]
https://github.com/alantech/highlightjs-alan
https://github.com/highlightjs/highlightjs-alan

_Are neither of these published on NPM?_  If there are truly different languages could we come up with a different name for the final package to remove any potential confusion users might have?

**Comment by joshgoebel** [comment]
Ref: https://github.com/highlightjs/highlightjs-alan/issues/6

**Comment by dfellis** [comment]
We didn't publish to NPM because we didn't want to just steal the name of the package since the other one got upstreamed into the project first.

We didn't want to give this repository a different name since our language name is just "Alan" and the other seems to go by "Alan IF" in their documentation.

**Comment by joshgoebel** [comment]
Yes, its' been suggested the other is renamed to `highlightjs-alan-if`, which sounds right so far.

**Comment by joshgoebel** [comment]
Renamed to `highlightjs-alan-if`. :-)  Thanks all!

I don't think right now there is a package for either?

- https://www.npmjs.com/package/highlightjs-alan-if (404)
- https://www.npmjs.com/package/highlightjs-alan (404)

**Comment by joshgoebel** [comment]
So is the way paved for your npm package now then?

**Comment by dfellis** [comment]
Sure. Give me a few minutes and this repo will be up in NPM.

**Comment by dfellis** [comment]
[This repo is now published](https://www.npmjs.com/package/highlightjs-alan). Thank you. :)
